---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Pull Docker Image
      docker_image:
        name: shubhanshi/spe-mini-project:{{tag}}
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: calculator-using-devops
        image: shubhanshi/spe-mini-project:{{tag}}
        state: started
        tty: yes
        interactive: yes

